version: '3'
services:
    php:
        image: php:8.1-cli
        volumes:
            - .:/app
        working_dir: /app
        command: php src/app.php
        stdin_open: true
        tty: true
        networks:
            - app-network

    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
        command: install
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env.example
        networks:
            - app-network

networks:
    app-network:
        driver: bridge