version: '3'
services:
    php:
        build: .
        volumes:
            - .:/app
        working_dir: /app
        command: php src/app.php
        stdin_open: true
        tty: true
        networks:
            - app-network

    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
        command: install
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        networks:
            - app-network

    cs-fixer:
        image: jakzal/phpqa:1.95.2
        volumes:
            - .:/app
        working_dir: /app
        command: php-cs-fixer fix src
        networks:
            - app-network


networks:
    app-network:
        driver: bridge