version: '3'
services:
    php:
        image: php:8.1-cli
        volumes:
            - .:/app
        working_dir: /app
        command: php src/app.php
        stdin_open: true
        tty: true

    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
        command: install
